generate-config:
  image: denoland/deno:latest
  stage: build
  script: deno run --unstable --allow-all --import-map ./import_map.json ./lib/es6_global/src/generate_config.js
  artifacts:
    paths:
      - generated-config.yml

child-pipeline:
  stage: test
  trigger:
    include:
      - artifact: generated-config.yml
        job: generate-config