generate-config:
  image: denoland/deno:alpine-1.14.3
  stage: build
  script:
    - apk update
    - apk add git
    - deno run --unstable --allow-all --import-map ./import_map.json ./lib/es6_global/src/generate_config.js
  artifacts:
    paths:
      - generated-config.yml

child-pipeline:
  stage: test
  trigger:
    include:
      - artifact: generated-config.yml
        job: generate-config