generate-config-manual:
  image: aivero/conan:focal-x86_64
  stage: build
  variables:
    mode: manual
    component: "*/*"
  script:
    - deno --version
    - deno run --unstable --allow-all --import-map ./import_map.json ./lib/es6_global/src/GenerateConfig.js
  artifacts:
    paths:
      - generated-config.yml 
      - lock.bundle
      - build_order.json
      - "*.lock"
child-pipeline-manual:
  stage: test
  trigger:
    include:
      - artifact: generated-config.yml
        job: generate-config-manual
generate-config-git:
  image: aivero/conan:focal-x86_64
  stage: build
  variables:
    mode: git
  script:
    - deno --version
    - deno run --unstable --allow-all --import-map ./import_map.json ./lib/es6_global/src/GenerateConfig.js
  artifacts:
    paths:
      - generated-config.yml 
      - lock.bundle
      - build_order.json
      - "*.lock"
child-pipeline-git:
  stage: test
  trigger:
    include:
      - artifact: generated-config.yml
        job: generate-config-git