generate-config:
  image: aivero/conan:bionic-x86_64
  stage: build
  script:
    - deno run --unstable --allow-all --import-map ./import_map.json ./lib/es6_global/src/GenerateConfig.js
  artifacts:
    paths:
      - generated-config.yml 
child-pipeline:
  stage: test
  trigger:
    include:
      - artifact: generated-config.yml
        job: generate-config