// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Seq from "../std/Seq.js";
import * as Task from "../std/Task.js";
import * as Detect from "../Detect.js";
import * as Belt_Array from "../../../../node_modules/rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "../../../../node_modules/rescript/lib/es6/belt_Option.js";
import * as Belt_Result from "../../../../node_modules/rescript/lib/es6/belt_Result.js";

function getJobs(zips) {
  return Task.resolve(Seq.array(Belt_Array.map(zips.filter(function (zip) {
                          return zip.mode === "command";
                        }), (function (zip) {
                        return Belt_Result.flatMap(Detect.getImage(zip), (function (image) {
                                      var match = zip.int.name;
                                      var match$1 = zip.int.cmds;
                                      if (match !== undefined && match$1 !== undefined) {
                                        var needs = zip.int.req;
                                        return {
                                                TAG: /* Ok */0,
                                                _0: {
                                                  name: match + "-" + zip.profile,
                                                  extends: undefined,
                                                  variables: undefined,
                                                  image: image,
                                                  tags: undefined,
                                                  script: match$1,
                                                  needs: needs !== undefined ? Belt_Array.map(needs, (function (need) {
                                                            return need + "-" + zip.profile;
                                                          })) : []
                                                }
                                              };
                                      }
                                      return {
                                              TAG: /* Error */1,
                                              _0: Belt_Option.getExn(zip.int.name) + ": name or cmds not specified"
                                            };
                                    }));
                      }))));
}

export {
  getJobs ,
  
}
/* No side effect */
