// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Array from "../std/Array.js";
import * as TaskResult from "../std/TaskResult.js";

function getInstances($$int) {
  return $$Array.map($$int.profiles, (function (profile) {
                return {
                        base: $$int,
                        profile: profile
                      };
              }));
}

function getJobs(ints) {
  return TaskResult.resolve($$Array.map($$Array.flatMap($$Array.filter(ints, (function ($$int) {
                            return $$int.mode === "command";
                          })), getInstances), (function (param) {
                    var profile = param.profile;
                    var match = param.base;
                    return {
                            name: match.name + "-" + profile,
                            extends: undefined,
                            variables: undefined,
                            image: match.image,
                            tags: undefined,
                            script: match.cmds,
                            needs: $$Array.map(match.reqs, (function (need) {
                                    return need + "-" + profile;
                                  })),
                            services: undefined
                          };
                  })));
}

export {
  getInstances ,
  getJobs ,
  
}
/* No side effect */
