// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Flat from "../std/flat.js";
import * as Task from "../std/task.js";
import * as Detect from "../detect.js";
import * as Belt_Array from "../../../../node_modules/rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "../../../../node_modules/rescript/lib/es6/belt_Option.js";

function getJobs(zips) {
  return Task.resolve(Flat.array(Belt_Array.map(zips.filter(function (zip) {
                          return zip.mode === "command";
                        }), (function (zip) {
                        var match = zip.int.name;
                        var match$1 = zip.int.cmds;
                        var match$2 = Detect.getImage(zip);
                        if (match !== undefined && match$1 !== undefined && match$2.TAG === /* Ok */0) {
                          var needs = zip.int.needs;
                          return {
                                  TAG: /* Ok */0,
                                  _0: {
                                    name: match + "-" + zip.profile,
                                    image: match$2._0,
                                    script: match$1,
                                    needs: needs !== undefined ? Belt_Array.map(needs, (function (need) {
                                              return need + "-" + zip.profile;
                                            })) : []
                                  }
                                };
                        }
                        if (match$2.TAG === /* Ok */0) {
                          return {
                                  TAG: /* Error */1,
                                  _0: Belt_Option.getExn(zip.int.name) + ": name or cmds not specified"
                                };
                        } else {
                          return {
                                  TAG: /* Error */1,
                                  _0: match$2._0
                                };
                        }
                      }))));
}

export {
  getJobs ,
  
}
/* No side effect */
