// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Task from "../std/Task.js";
import * as $$Array from "../std/Array.js";
import * as Result from "../std/Result.js";

function getInstances($$int) {
  return {
          TAG: /* Ok */0,
          _0: $$Array.map($$int.profiles, (function (profile) {
                  return {
                          base: $$int,
                          profile: profile
                        };
                }))
        };
}

function getJobs(ints) {
  return Task.resolve(Result.flatMap(Result.seq($$Array.map($$Array.filter(ints, (function ($$int) {
                                return $$int.mode === "command";
                              })), getInstances)), (function (ints) {
                    var ints$1 = $$Array.flatten(ints);
                    return Result.seq($$Array.map(ints$1, (function (param) {
                                      var profile = param.profile;
                                      var match = param.base;
                                      return {
                                              TAG: /* Ok */0,
                                              _0: {
                                                name: match.name + "-" + profile,
                                                extends: undefined,
                                                variables: undefined,
                                                image: match.image,
                                                tags: undefined,
                                                script: match.cmds,
                                                needs: $$Array.map(match.reqs, (function (need) {
                                                        return need + "-" + profile;
                                                      })),
                                                services: undefined
                                              }
                                            };
                                    })));
                  })));
}

export {
  getInstances ,
  getJobs ,
  
}
/* No side effect */
