// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Conan from "./conan.js";
import * as Detect from "../detect.js";
import * as Belt_Array from "../../../../node_modules/rescript/lib/es6/belt_Array.js";

function getJobs(zips) {
  return Belt_Array.map(zips, (function (zip) {
                var $$int = zip.int;
                var args = Belt_Array.joinWith(Conan.getArgs($$int), " ", (function (str) {
                        return str;
                      }));
                var match = $$int.name;
                var match$1 = $$int.tag;
                var match$2 = $$int.branch;
                var exit = 0;
                if (match !== undefined) {
                  if (match$1 !== undefined) {
                    if (match$2 === undefined) {
                      exit = 1;
                    }
                    
                  } else if (match$2 !== undefined) {
                    "ghcr.io/aivero/" + match + "/" + zip.profile.toLowerCase() + ":" + match$2;
                  } else {
                    exit = 1;
                  }
                } else {
                  exit = 1;
                }
                if (exit === 1) {
                  throw {
                        RE_EXN_ID: "Match_failure",
                        _1: [
                          "docker.res",
                          5,
                          14
                        ],
                        Error: new Error()
                      };
                }
                var match$3 = $$int.folder;
                var match$4 = $$int.branch;
                var match$5 = $$int.conanInstall;
                if (match$3 !== undefined) {
                  if (match$4 !== undefined) {
                    if (match$5 !== undefined) {
                      Belt_Array.map(match$5, (function (pkg) {
                              return [
                                      "mkdir -p " + match$3 + "/install || true",
                                      "conan install " + args + pkg + "/" + match$4 + "@ -if " + match$3 + "/install/" + pkg
                                    ];
                            }));
                    } else {
                      [];
                    }
                  } else {
                    [];
                  }
                }
                var match$6 = $$int.cmds;
                var match$7 = Detect.getImage(zip);
                if (match$6 !== undefined && match$7.TAG === /* Ok */0) {
                  var needs = zip.int.needs;
                  return {
                          TAG: /* Ok */0,
                          _0: {
                            name: "foo",
                            image: match$7._0,
                            script: match$6,
                            needs: needs !== undefined ? needs : []
                          }
                        };
                }
                if (match$7.TAG === /* Ok */0) {
                  return {
                          TAG: /* Error */1,
                          _0: "No commands specified"
                        };
                } else {
                  return {
                          TAG: /* Error */1,
                          _0: match$7._0
                        };
                }
              }));
}

export {
  getJobs ,
  
}
/* Conan Not a pure module */
