// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Profile from "../Profile.js";
import * as Task$Std from "@prefix_re/std/lib/es6/src/Task.js";
import * as Array$Std from "@prefix_re/std/lib/es6/src/Array.js";
import * as Result$Std from "@prefix_re/std/lib/es6/src/Result.js";

function getJobs(ints) {
  return Task$Std.fromResult(Result$Std.seq(Array$Std.flatMap(Array$Std.filter(ints, (function ($$int) {
                            return $$int.mode === "command";
                          })), (function (param) {
                        var cache = param.cache;
                        var script = param.script;
                        var needs = param.needs;
                        var folder = param.folder;
                        var version = param.version;
                        var name = param.name;
                        return Array$Std.map(param.profiles, (function (profile) {
                                      return Result$Std.map(Profile.getImage(profile), (function (image) {
                                                    return [
                                                            name + "/" + version,
                                                            {
                                                              extends: undefined,
                                                              variables: undefined,
                                                              image: image,
                                                              tags: undefined,
                                                              script: Array$Std.concat(["cd " + folder], script),
                                                              needs: Array$Std.uniq(needs),
                                                              services: undefined,
                                                              cache: cache
                                                            }
                                                          ];
                                                  }));
                                    }));
                      }))));
}

export {
  getJobs ,
  
}
/* No side effect */
