// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jobt from "./Jobt.js";
import * as Profile from "../Profile.js";
import * as Task$Std from "@prefix_re/std/lib/es6/src/Task.js";
import * as Array$Std from "@prefix_re/std/lib/es6/src/Array.js";
import * as Result$Std from "@prefix_re/std/lib/es6/src/Result.js";

function getJobs(ints) {
  return Task$Std.fromResult(Result$Std.seq(Array$Std.flatMap(Array$Std.filter(ints, (function ($$int) {
                            return $$int.mode === "command";
                          })), (function (param) {
                        var cache = param.cache;
                        var image = param.image;
                        var script = param.script;
                        var needs = param.needs;
                        var folder = param.folder;
                        var version = param.version;
                        var name = param.name;
                        return Array$Std.map(param.profiles, (function (profile) {
                                      var image$1 = image !== undefined ? ({
                                            TAG: /* Ok */0,
                                            _0: image
                                          }) : Profile.getImage(profile);
                                      return Result$Std.map(image$1, (function (image) {
                                                    return [
                                                            name + "/" + version,
                                                            {
                                                              extends: Jobt.$$default.extends,
                                                              variables: Jobt.$$default.variables,
                                                              image: image,
                                                              tags: Jobt.$$default.tags,
                                                              before_script: Jobt.$$default.before_script,
                                                              script: Array$Std.concat(["cd " + folder], script),
                                                              after_script: Jobt.$$default.after_script,
                                                              needs: Array$Std.uniq(needs),
                                                              services: Jobt.$$default.services,
                                                              cache: cache,
                                                              retry: Jobt.$$default.retry,
                                                              artifacts: Jobt.$$default.artifacts
                                                            }
                                                          ];
                                                  }));
                                    }));
                      }))));
}

export {
  getJobs ,
  
}
/* No side effect */
