// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jobt from "./Jobt.js";
import * as Conan from "./Conan.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as Docker from "./Docker.js";
import * as Command from "./Command.js";
import * as Hash$Std from "@aivero/std/lib/es6/src/Deno/Hash.js";
import * as Array$Std from "@aivero/std/lib/es6/src/Array.js";
import * as Async$Std from "@aivero/std/lib/es6/src/Async.js";
import * as Result$Std from "@aivero/std/lib/es6/src/Result.js";

function parseMode(str) {
  switch (str) {
    case "conan" :
        return "conan";
    case "docker" :
        return "docker";
    default:
      return "command";
  }
}

function hashN(__x) {
  return Hash$Std.hashN(__x, 4);
}

function handleDuplicates(jobs) {
  return Array$Std.flatMap(Array$Std.groupBy(jobs, (function (param) {
                    return param[0];
                  })), (function (param) {
                var group = param[1];
                if (group.length === 1) {
                  return [group[0]];
                }
                var jobs = Array$Std.map(group, (function (param) {
                        var job = param[1];
                        return [
                                param[0] + "@" + Hash$Std.hashN(job, 4),
                                job
                              ];
                      }));
                return Array$Std.concat(jobs, [[
                              param[0],
                              {
                                extends: [".git-strat-none"],
                                variables: Jobt.$$default.variables,
                                image: Jobt.$$default.image,
                                tags: ["saas-linux-large-amd64"],
                                before_script: Jobt.$$default.before_script,
                                script: ["echo"],
                                after_script: Jobt.$$default.after_script,
                                needs: Array$Std.uniq(Array$Std.map(jobs, (function (param) {
                                            return param[0];
                                          }))),
                                services: Jobt.$$default.services,
                                cache: Jobt.$$default.cache,
                                retry: Jobt.$$default.retry,
                                artifacts: Jobt.$$default.artifacts,
                                when: Jobt.$$default.when,
                                allow_failure: Jobt.$$default.allow_failure,
                                rules: Jobt.$$default.rules,
                                interruptible: Jobt.$$default.interruptible
                              }
                            ]]);
              }));
}

function load(ints) {
  return Async$Std.map(Promise.all(Array$Std.map([
                      Command.getJobs,
                      Conan.getJobs,
                      Docker.getJobs
                    ], (function (f) {
                        return Curry._1(f, ints);
                      }))), (function (jobs) {
                return Result$Std.map(Result$Std.seq(jobs), (function (jobs) {
                              return handleDuplicates(Array$Std.flat(jobs));
                            }));
              }));
}

var hashLength = 4;

export {
  parseMode ,
  hashLength ,
  hashN ,
  handleDuplicates ,
  load ,
  
}
/* Conan Not a pure module */
