// Generated by ReScript, PLEASE EDIT WITH CARE


var $$default = {
  extends: undefined,
  variables: undefined,
  image: undefined,
  tags: undefined,
  before_script: undefined,
  script: undefined,
  after_script: undefined,
  needs: undefined,
  services: undefined,
  cache: undefined,
  retry: undefined,
  artifacts: undefined,
  when: undefined,
  allow_failure: undefined,
  rules: undefined,
  interruptible: true
};

export {
  $$default ,
  $$default as default,
  
}
/* No side effect */
