// Generated by ReScript, PLEASE EDIT WITH CARE


var $$default = {
  extends: undefined,
  variables: undefined,
  image: undefined,
  tags: undefined,
  script: undefined,
  needs: undefined,
  services: undefined,
  cache: undefined,
  retry: undefined,
  artifacts: undefined
};

export {
  $$default ,
  $$default as default,
  
}
/* No side effect */
