// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";
import * as $$File from "./std/File.js";
import * as Flat from "./std/Flat.js";
import * as Path from "path";
import * as Yaml from "yaml";
import * as Instance from "./Instance.js";
import * as Belt_Array from "../../../node_modules/rescript/lib/es6/belt_Array.js";
import * as Belt_Result from "../../../node_modules/rescript/lib/es6/belt_Result.js";

var name = "devops.yml";

function find(_dir) {
  while(true) {
    var dir = _dir;
    var path = Path.join(dir, name);
    if (Fs.existsSync(path)) {
      return path;
    }
    if (dir === ".") {
      return ;
    }
    _dir = Path.dirname(dir);
    continue ;
  };
}

function load(content, path) {
  var partial_arg = Path.dirname(path);
  return Belt_Array.map(Yaml.parse(content), (function (param) {
                return Instance.create(partial_arg, param);
              }));
}

function loadFile(path) {
  return Belt_Result.flatMap($$File.read(path), (function (content) {
                return Flat.array(load(content, path));
              }));
}

export {
  name ,
  find ,
  load ,
  loadFile ,
  
}
/* fs Not a pure module */
