// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mode from "./mode/Mode.js";
import * as Task from "./std/Task.js";
import * as Gitlab from "./Gitlab.js";

function main(param) {
  Task.flatMap(Mode.load(undefined), (function (res) {
          if (res.TAG === /* Ok */0) {
            Gitlab.generate(res._0);
            return Task.resolve((console.log("Ok"), undefined));
          }
          console.log("Error: " + res._0.toString());
          return Task.resolve((Deno.exit(1), undefined));
        }));
  
}

main(undefined);

export {
  main ,
  
}
/*  Not a pure module */
