// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Sys from "./std/Sys.js";
import * as Mode from "./mode/Mode.js";
import * as Task from "./std/Task.js";
import * as Gitlab from "./Gitlab.js";
import * as Console from "./std/Console.js";

function main(param) {
  Task.mapError(Task.map(Mode.load(undefined), (function (jobs) {
              Gitlab.generate(jobs);
              return Console.log("Ok");
            })), (function (msg) {
          Console.log("Error: " + msg);
          return Sys.exit(1);
        }));
  
}

main(undefined);

export {
  main ,
  
}
/*  Not a pure module */
