// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mode from "./mode/mode.js";
import * as Task from "./std/task.js";
import * as Gitlab from "./gitlab.js";

function main(param) {
  Task.flatMap(Mode.load(undefined), (function (res) {
          if (res.TAG !== /* Ok */0) {
            return Task.resolve((console.log("Error: " + res._0.toString()), undefined));
          }
          Gitlab.generate(res._0);
          return Task.resolve((console.log("Ok"), undefined));
        }));
  
}

main(undefined);

export {
  main ,
  
}
/*  Not a pure module */
