// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Sys from "./std/Sys.js";
import * as Mode from "./mode/Mode.js";
import * as Task from "./std/Task.js";
import * as Gitlab from "./Gitlab.js";
import * as Console from "./std/Console.js";

function main(param) {
  Task.map(Mode.load(undefined), (function (res) {
          if (res.TAG === /* Ok */0) {
            Gitlab.generate(res._0);
            return Console.log("Ok");
          }
          Console.log("Error: " + res._0.toString());
          return Sys.exit(1);
        }));
  
}

main(undefined);

export {
  main ,
  
}
/*  Not a pure module */
