// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$File from "./std/File.js";
import * as Curry from "../../../node_modules/rescript/lib/es6/curry.js";
import * as Belt_Array from "../../../node_modules/rescript/lib/es6/belt_Array.js";

function chunk(array, size) {
  var cur = Belt_Array.slice(array, 0, size);
  var rest = Belt_Array.slice(array, size, array.length - size | 0);
  var match = rest.length;
  if (match !== 0) {
    return Belt_Array.concat([cur], chunk(rest, size));
  } else {
    return [cur];
  }
}

function generateJob(job) {
  var image = job.image;
  var script = job.script;
  return Belt_Array.concatMany([
              [
                job.name + ":",
                "  needs: [" + Belt_Array.joinWith(job.needs, ", ", (function (a) {
                        return a;
                      })) + "]"
              ],
              image !== undefined ? ["  image: " + image] : [],
              script !== undefined ? Belt_Array.concat(["  script:"], Belt_Array.map(script, (function (l) {
                            return "    - " + l;
                          }))) : []
            ]);
}

function generate(jobs) {
  var partial_arg = new TextEncoder();
  var encode = function (param) {
    return partial_arg.encode(param);
  };
  var jobs$1 = jobs.length !== 0 ? jobs : [{
        name: "empty",
        image: undefined,
        script: ["echo"],
        needs: []
      }];
  return $$File.write(Curry._1(encode, Belt_Array.joinWith(Belt_Array.concatMany(Belt_Array.map(jobs$1, generateJob)), "\n", (function (a) {
                        return a;
                      }))), "generated-config.yml");
}

export {
  chunk ,
  generateJob ,
  generate ,
  
}
/* File Not a pure module */
