// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$File from "./std/file.js";
import * as Curry from "../../../node_modules/rescript/lib/es6/curry.js";
import * as Belt_Array from "../../../node_modules/rescript/lib/es6/belt_Array.js";

function generate(jobs) {
  var partial_arg = new TextEncoder();
  var encode = function (param) {
    return partial_arg.encode(param);
  };
  var jobs$1 = jobs.length !== 0 ? jobs : [{
        name: "empty",
        image: undefined,
        script: [],
        needs: []
      }];
  $$File.write(Curry._1(encode, Belt_Array.joinWith(Belt_Array.concatMany(Belt_Array.map(jobs$1, (function (job) {
                          var image = job.image;
                          return Belt_Array.concat([
                                      job.name + ":",
                                      "  needs: [" + Belt_Array.joinWith(job.needs, ", ", (function (a) {
                                              return a;
                                            })) + "]",
                                      "  script:",
                                      Belt_Array.joinWith(Belt_Array.map(job.script, (function (l) {
                                                  return "    - " + l;
                                                })), "\n", (function (a) {
                                              return a;
                                            }))
                                    ], image !== undefined ? ["  image: " + image] : []);
                        }))), "\n", (function (a) {
                  return a;
                }))), "generated-config.yml");
  
}

export {
  generate ,
  
}
/* File Not a pure module */
