// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Seq from "./std/Seq.js";
import * as Belt_List from "../../../node_modules/rescript/lib/es6/belt_List.js";
import * as Belt_Result from "../../../node_modules/rescript/lib/es6/belt_Result.js";

function getImage(param) {
  var profile = param.profile;
  var triple = Belt_List.fromArray(profile.split("-"));
  var os;
  if (triple) {
    var exit = 0;
    var match = triple.tl;
    if (match && match.hd === "musl") {
      os = {
        TAG: /* Ok */0,
        _0: "alpine"
      };
    } else {
      exit = 1;
    }
    if (exit === 1) {
      switch (triple.hd) {
        case "macos" :
            os = {
              TAG: /* Ok */0,
              _0: "macos"
            };
            break;
        case "linux" :
        case "wasi" :
            os = {
              TAG: /* Ok */0,
              _0: "focal"
            };
            break;
        case "windows" :
            os = {
              TAG: /* Ok */0,
              _0: "windows"
            };
            break;
        default:
          os = {
            TAG: /* Error */1,
            _0: "Could not detect image os for profile: " + profile
          };
      }
    }
    
  } else {
    os = {
      TAG: /* Error */1,
      _0: "Could not detect image os for profile: " + profile
    };
  }
  var arch;
  if (triple) {
    var match$1 = triple.tl;
    if (match$1) {
      switch (match$1.hd) {
        case "armv8" :
            arch = {
              TAG: /* Ok */0,
              _0: "armv8"
            };
            break;
        case "wasm" :
        case "x86_64" :
            arch = {
              TAG: /* Ok */0,
              _0: "x86_64"
            };
            break;
        default:
          arch = {
            TAG: /* Error */1,
            _0: "Could not detect image arch for profile: " + profile
          };
      }
    } else {
      arch = {
        TAG: /* Error */1,
        _0: "Could not detect image arch for profile: " + profile
      };
    }
  } else {
    arch = {
      TAG: /* Error */1,
      _0: "Could not detect image arch for profile: " + profile
    };
  }
  var end = param.int.bootstrap ? "-bootstrap" : "";
  return Belt_Result.map(Seq.result2([
                  os,
                  arch
                ]), (function (param) {
                return "aivero/conan:" + param[0] + "-" + param[1] + end;
              }));
}

function getRunnerTags(profile) {
  var match = profile.split("-");
  if (match.length !== 2) {
    throw {
          RE_EXN_ID: "Match_failure",
          _1: [
            "Profile.res",
            31,
            6
          ],
          Error: new Error()
        };
  }
  var arch = match[1];
  switch (arch) {
    case "armv8" :
        return {
                TAG: /* Ok */0,
                _0: [
                  "ARM64",
                  "aws"
                ]
              };
    case "wasm" :
    case "x86_64" :
        return {
                TAG: /* Ok */0,
                _0: [
                  "X64",
                  "aws"
                ]
              };
    default:
      return {
              TAG: /* Error */1,
              _0: "Could detect runner tags for profile: " + profile
            };
  }
}

function getDockerPlatform(profile) {
  var match = profile.split("-");
  if (match.length !== 2) {
    throw {
          RE_EXN_ID: "Match_failure",
          _1: [
            "Profile.res",
            42,
            6
          ],
          Error: new Error()
        };
  }
  var os = match[0];
  var arch = match[1];
  var os$1;
  switch (os) {
    case "linux" :
        os$1 = {
          TAG: /* Ok */0,
          _0: "linux"
        };
        break;
    case "macos" :
        os$1 = {
          TAG: /* Error */1,
          _0: "MacOS / Darwin builds are not yet supported"
        };
        break;
    case "windows" :
        os$1 = {
          TAG: /* Error */1,
          _0: "Windows builds are not yet supported"
        };
        break;
    default:
      os$1 = {
        TAG: /* Error */1,
        _0: "Could not parse profile " + profile + " to an os."
      };
  }
  var arch$1;
  switch (arch) {
    case "86-64" :
    case "86_64" :
        arch$1 = {
          TAG: /* Ok */0,
          _0: "amd64"
        };
        break;
    case "arm7" :
    case "armhf" :
        arch$1 = {
          TAG: /* Ok */0,
          _0: "arm/v7"
        };
        break;
    case "arm64" :
    case "armv8" :
        arch$1 = {
          TAG: /* Ok */0,
          _0: "arm64"
        };
        break;
    default:
      arch$1 = {
        TAG: /* Error */1,
        _0: "Could not parse profile " + profile + " to an arch."
      };
  }
  return Belt_Result.map(Seq.result2([
                  os$1,
                  arch$1
                ]), (function (param) {
                return param[0] + " /" + param[1];
              }));
}

export {
  getImage ,
  getRunnerTags ,
  getDockerPlatform ,
  
}
/* No side effect */
