// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Proc from "./std/Proc.js";
import * as Task from "./std/Task.js";
import * as Curry from "../../../node_modules/rescript/lib/es6/curry.js";
import * as Belt_Array from "../../../node_modules/rescript/lib/es6/belt_Array.js";

function resolve(prim) {
  return Promise.resolve(prim);
}

function reject(prim) {
  return Promise.reject(prim);
}

function $$catch(a, f) {
  return a.catch(Curry.__1(f));
}

function map(a, fn) {
  return a.then(function (v) {
              return Promise.resolve(Curry._1(fn, v));
            });
}

function flatMap(a, fn) {
  return a.then(Curry.__1(fn));
}

function catchResolve(a, fn) {
  return a.catch(function (e) {
              return Promise.resolve(Curry._1(fn, e));
            });
}

function sleep(a, ms) {
  return a.then(function (res) {
              return new Promise((function (resolve) {
                            setTimeout((function (param) {
                                    return Curry._1(resolve, res);
                                  }), ms);
                            
                          }));
            });
}

function pool(tasks, count) {
  var curTasks = Promise.all(Belt_Array.map(Belt_Array.slice(tasks, 0, count), (function (f) {
              return new Promise((function (resolve) {
                            return Curry._1(resolve, Curry._1(f, undefined));
                          }));
            })));
  var rest = Belt_Array.slice(tasks, count, tasks.length - count | 0);
  console.log("pool: " + String(rest.length));
  var match = rest.length;
  if (match !== 0) {
    return curTasks.then(function (res1) {
                return map(pool(rest, count), (function (res2) {
                              return Belt_Array.concatMany([
                                          res1,
                                          res2
                                        ]);
                            }));
              });
  } else {
    return curTasks;
  }
}

var l = [
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14
];

var tasks = Belt_Array.map(l, (function (i, param) {
        return Proc.run([
                    "sleep",
                    String(i)
                  ]);
      }));

var bla = Task.map(pool(tasks, 10), (function (prim) {
        console.log(prim);
        
      }));

var foo = Task.map(bla, (function (param) {
        return Task.map(pool(tasks, 10), (function (prim) {
                      console.log(prim);
                      
                    }));
      }));

export {
  resolve ,
  reject ,
  $$catch ,
  map ,
  flatMap ,
  catchResolve ,
  sleep ,
  pool ,
  l ,
  tasks ,
  bla ,
  foo ,
  
}
/* tasks Not a pure module */
