// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";
import * as Path from "path";
import * as File$Std from "@prefix_re/std/lib/es6/src/Deno/File.js";
import * as Instance from "./Instance.js";
import * as Yaml$Std from "@prefix_re/std/lib/es6/src/Deno/Yaml.js";
import * as Result$Std from "@prefix_re/std/lib/es6/src/Result.js";

var name = "devops.yml";

function find(_dir) {
  while(true) {
    var dir = _dir;
    var path = Path.join(dir, name);
    if (Fs.existsSync(path)) {
      return path;
    }
    if (dir === ".") {
      return ;
    }
    _dir = Path.dirname(dir);
    continue ;
  };
}

function load(content, path) {
  return Yaml$Std.map(Yaml$Std.parse(content), (function (__x) {
                return Instance.create(__x, Path.dirname(path));
              }));
}

function loadFile(path) {
  return Result$Std.map(File$Std.read(path), (function (__x) {
                return load(__x, path);
              }));
}

export {
  name ,
  find ,
  load ,
  loadFile ,
  
}
/* fs Not a pure module */
