// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";
import * as $$File from "./std/File.js";
import * as Yaml from "./std/Yaml.js";
import * as Path from "path";
import * as Result from "./std/Result.js";
import * as Instance from "./Instance.js";

var name = "devops.yml";

function find(_dir) {
  while(true) {
    var dir = _dir;
    var path = Path.join(dir, name);
    if (Fs.existsSync(path)) {
      return path;
    }
    if (dir === ".") {
      return ;
    }
    _dir = Path.dirname(dir);
    continue ;
  };
}

function load(content, path) {
  return Yaml.map(Yaml.parse(content), (function (__x) {
                return Instance.create(__x, Path.dirname(path));
              }));
}

function loadFile(path) {
  return Result.map($$File.read(path), (function (__x) {
                return load(__x, path);
              }));
}

export {
  name ,
  find ,
  load ,
  loadFile ,
  
}
/* fs Not a pure module */
