// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mode from "./mode/Mode.js";
import * as Gitlab from "./Gitlab.js";
import * as Sys$Std from "@aivero/std/lib/es6/src/Deno/Sys.js";
import * as Task$Std from "@aivero/std/lib/es6/src/Task.js";
import * as Console$Std from "@aivero/std/lib/es6/src/Console.js";

function main(param) {
  Task$Std.mapError(Task$Std.map(Mode.load(undefined), (function (jobs) {
              Gitlab.generate(jobs);
              return Console$Std.log("Ok");
            })), (function (msg) {
          Console$Std.log("Error: " + msg);
          return Sys$Std.exit(1);
        }));
  
}

main(undefined);

export {
  main ,
  
}
/*  Not a pure module */
