// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Array$Std from "@prefix_re/std/lib/es6/src/Array.js";
import * as Console$Std from "@prefix_re/std/lib/es6/src/Console.js";

var one = [
  "one",
  "two"
];

var two = [
  "one",
  "two"
];

var jobs = [
  one,
  two
];

var theSame = Array$Std.reduce(Array$Std.map(jobs, (function (needs) {
            return Caml_obj.caml_equal(needs, one);
          })), (function (acc, theSame) {
        if (acc) {
          return theSame;
        } else {
          return false;
        }
      }), true);

if (theSame) {
  Console$Std.log("Yooo");
}

export {
  one ,
  two ,
  jobs ,
  theSame ,
  
}
/* theSame Not a pure module */
