// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Task from "../std/Task.js";
import * as $$Array from "../std/Array.js";
import * as $$String from "../std/String.js";
import * as Console from "../std/Console.js";

function filter(ints, comps) {
  return $$Array.filter(ints, (function (param) {
                var version = param.version;
                var name = param.name;
                if ($$Array.some(comps, (function (comp) {
                          var match = comp[0];
                          var match$1 = comp[1];
                          if (match === undefined) {
                            return false;
                          }
                          if (match === "*" && match$1 !== undefined) {
                            return match$1 === "*" ? true : match$1 === version;
                          }
                          return match$1 !== undefined && match$1 !== "*" ? false : match === name;
                        }))) {
                  return !$$Array.some(comps, (function (comp) {
                                var cname = comp[0];
                                if (cname !== undefined && $$String.startsWith(cname, "-")) {
                                  return $$String.sliceToEnd(cname, 1) === name;
                                } else {
                                  return false;
                                }
                              }));
                } else {
                  return false;
                }
              }));
}

function findInts(allInts) {
  Console.log("Manual Mode: Create instances from manual args");
  var comps = Deno.env.get("component");
  var comps$1 = (comps == null) ? [] : (Console.log("Building components: " + comps), $$Array.map($$String.split(comps, ","), (function (comp) {
              return $$String.split(comp, "/");
            })));
  return Task.map(allInts, (function (ints) {
                return filter(ints, comps$1);
              }));
}

export {
  filter ,
  findInts ,
  
}
/* No side effect */
