// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "../../../../node_modules/rescript/lib/es6/js_dict.js";

var entries = Js_dict.entries;

var fromArray = Js_dict.fromArray;

var get = Js_dict.get;

export {
  entries ,
  fromArray ,
  get ,
  
}
/* No side effect */
