// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Array from "./Array.js";
import * as Js_dict from "../../../../node_modules/rescript/lib/es6/js_dict.js";

function map(d) {
  var partial_arg = Js_dict.entries(d);
  return function (param) {
    return $$Array.map(partial_arg, param);
  };
}

var entries = Js_dict.entries;

var fromArray = Js_dict.fromArray;

var get = Js_dict.get;

export {
  entries ,
  fromArray ,
  get ,
  map ,
  
}
/* No side effect */
