// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "../../../../node_modules/rescript/lib/es6/belt_Array.js";

var array = Belt_Array.concatMany;

export {
  array ,
  
}
/* No side effect */
