// Generated by ReScript, PLEASE EDIT WITH CARE

import Hash from "hash";
import * as $$String from "../../../../node_modules/rescript/lib/es6/string.js";

function hashN(data, n) {
  return $$String.sub(Hash(data), 0, n);
}

export {
  hashN ,
  
}
/* hash Not a pure module */
