// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Array from "./Array.js";
import * as Caml_option from "../../../../node_modules/rescript/lib/es6/caml_option.js";

function toResult(o, err) {
  if (o !== undefined) {
    return {
            TAG: /* Ok */0,
            _0: Caml_option.valFromOption(o)
          };
  } else {
    return {
            TAG: /* Error */1,
            _0: err
          };
  }
}

function seq(a) {
  return $$Array.reduce(a, (function (a, e) {
                if (a !== undefined && e !== undefined) {
                  return $$Array.concat(a, [Caml_option.valFromOption(e)]);
                }
                
              }), []);
}

function seq2(param) {
  var a2 = param[1];
  var a1 = param[0];
  if (a1 !== undefined && a2 !== undefined) {
    return [
            Caml_option.valFromOption(a1),
            Caml_option.valFromOption(a2)
          ];
  }
  
}

function seq3(param) {
  var a3 = param[2];
  var a2 = param[1];
  var a1 = param[0];
  if (a1 !== undefined && a2 !== undefined && a3 !== undefined) {
    return [
            Caml_option.valFromOption(a1),
            Caml_option.valFromOption(a2),
            Caml_option.valFromOption(a3)
          ];
  }
  
}

function seq4(param) {
  var a4 = param[3];
  var a3 = param[2];
  var a2 = param[1];
  var a1 = param[0];
  if (a1 !== undefined && a2 !== undefined && a3 !== undefined && a4 !== undefined) {
    return [
            Caml_option.valFromOption(a1),
            Caml_option.valFromOption(a2),
            Caml_option.valFromOption(a3),
            Caml_option.valFromOption(a4)
          ];
  }
  
}

export {
  toResult ,
  seq ,
  seq2 ,
  seq3 ,
  seq4 ,
  
}
/* No side effect */
