// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Task from "./Task.js";
import * as Belt_Array from "../../../../node_modules/rescript/lib/es6/belt_Array.js";

function run(cmd) {
  console.log("Running command: " + Belt_Array.joinWith(cmd, " ", (function (a) {
              return a;
            })));
  var proc = Deno.run({
        cmd: cmd,
        stdout: "piped",
        stderr: "piped"
      });
  var status = proc.status();
  var output = proc.output();
  var stderrOutput = proc.stderrOutput();
  return Task.map(Promise.all([
                  status,
                  output,
                  stderrOutput
                ]), (function (param) {
                var code = param[0].code;
                var decoder = new TextDecoder();
                var output = decoder.decode(param[1]);
                var errOutput = decoder.decode(param[2]);
                if (code === 0) {
                  return {
                          TAG: /* Ok */0,
                          _0: output
                        };
                } else {
                  return {
                          TAG: /* Error */1,
                          _0: errOutput + " (Exit code: " + String(code) + ")"
                        };
                }
              }));
}

export {
  run ,
  
}
/* No side effect */
