// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Task from "./Task.js";
import * as Belt_Array from "../../../../node_modules/rescript/lib/es6/belt_Array.js";

function run(cmd) {
  console.log("Running command: " + Belt_Array.joinWith(cmd, " ", (function (a) {
              return a;
            })));
  var p = Deno.run({
        cmd: cmd,
        stdout: "piped",
        stderr: "piped"
      });
  return Task.flatMap(p.status(), (function (param) {
                var code = param.code;
                var output = p.output();
                var stderrOutput = p.stderrOutput();
                return Task.map(code === 0 ? output : stderrOutput, (function (output) {
                              var decoded = new TextDecoder().decode(output);
                              if (code === 0) {
                                return {
                                        TAG: /* Ok */0,
                                        _0: decoded
                                      };
                              } else {
                                return {
                                        TAG: /* Error */1,
                                        _0: decoded + " (Exit code: " + String(code) + ")"
                                      };
                              }
                            }));
              }));
}

export {
  run ,
  
}
/* No side effect */
