// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Task from "./Task.js";
import * as Belt_Result from "../../../../node_modules/rescript/lib/es6/belt_Result.js";

function resolve(prim) {
  return Promise.resolve(prim);
}

function map(a, fn) {
  return Task.map(a, (function (res) {
                return Belt_Result.map(res, fn);
              }));
}

function flatMap(a, fn) {
  return Task.map(a, (function (res) {
                return Belt_Result.flatMap(res, fn);
              }));
}

export {
  resolve ,
  map ,
  flatMap ,
  
}
/* No side effect */
