// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "../../../../node_modules/rescript/lib/es6/curry.js";

function resolve(prim) {
  return Promise.resolve(prim);
}

function reject(prim) {
  return Promise.reject(prim);
}

function $$catch(a, f) {
  return a.catch(Curry.__1(f));
}

function map(a, fn) {
  return a.then(function (v) {
              return Promise.resolve(Curry._1(fn, v));
            });
}

function flatMap(a, fn) {
  return a.then(Curry.__1(fn));
}

function catchResolve(a, fn) {
  return a.catch(function (e) {
              return Promise.resolve(Curry._1(fn, e));
            });
}

function sleep(a, ms) {
  return a.then(function (res) {
              return new Promise((function (resolve) {
                            setTimeout((function (param) {
                                    return Curry._1(resolve, res);
                                  }), ms);
                            
                          }));
            });
}

export {
  resolve ,
  reject ,
  $$catch ,
  map ,
  flatMap ,
  catchResolve ,
  sleep ,
  
}
/* No side effect */
