// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "../../../../node_modules/rescript/lib/es6/curry.js";

function map2(param, fn) {
  return [
          Curry._1(fn, param[0]),
          Curry._1(fn, param[1])
        ];
}

function map3(param, fn) {
  return [
          Curry._1(fn, param[0]),
          Curry._1(fn, param[1]),
          Curry._1(fn, param[2])
        ];
}

function map4(param, fn) {
  return [
          Curry._1(fn, param[0]),
          Curry._1(fn, param[1]),
          Curry._1(fn, param[2]),
          Curry._1(fn, param[3])
        ];
}

export {
  map2 ,
  map3 ,
  map4 ,
  
}
/* No side effect */
