// Generated by ReScript, PLEASE EDIT WITH CARE

import Hash from "hash";
import * as $$String from "./String.js";

function hashN(data, n) {
  return $$String.slice(Hash(data), 0, n);
}

export {
  hashN ,
  
}
/* hash Not a pure module */
