// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Array from "./Array.js";

function read(path) {
  return $$Array.from(Deno.readDirSync(path));
}

export {
  read ,
  
}
/* No side effect */
