// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Git from "./git.js";
import * as Job from "../job/job.js";
import * as Flat from "../std/flat.js";
import * as Task from "../std/task.js";
import * as Manual from "./manual.js";
import * as Instance from "../instance.js";
import * as Belt_Result from "../../../../node_modules/rescript/lib/es6/belt_Result.js";

function load(param) {
  var kind = Deno.env.get("mode");
  var ints = (kind == null) || kind !== "manual" ? Git.findInts(undefined) : Manual.findInts(undefined);
  return Flat.task(Task.map(ints, (function (ints) {
                    return Belt_Result.flatMap(ints, (function (ints) {
                                  return Job.load(Instance.zip(ints));
                                }));
                  })));
}

export {
  load ,
  
}
/* Git Not a pure module */
